version: '3.8'

services:
  quiz-app-pg:
    image: postgres:latest
    container_name: quiz-app-pg
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - quiz-app-pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  quiz-app-pgadmin:
    image: dpage/pgadmin4:latest
    container_name: quiz-app-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - quiz-app-pg

  minio:
    image: minio/minio:latest
    container_name: quiz-app-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_REGION: ${MINIO_REGION}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - quiz-app-minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/ready"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio-init:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: [
      "sh","-c",
      "
      /bin/mc alias set local http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD} && \
      /bin/mc mb -p local/${MINIO_BUCKET} || true && \
      
      /bin/mc anonymous set download local/${MINIO_BUCKET} >/dev/null 2>&1 || true
      "
    ]

volumes:
  quiz-app-pg_data:
  quiz-app-minio_data: